[project] :bookmark: Bump and release version 21.1.0
Signed-off-by: palexdev <alessandro.parisi406@gmail.com>

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -17,7 +17,13 @@ jobs:
     steps:
       - name: Extract version
         id: extract
-        run: echo "ver=$(echo ${{ github.event.head_commit.message }} | sed -n 's/.*version \([0-9]\+\.[0-9]\+\.[0-9]\+\).*/\1/p')" >> "$GITHUB_OUTPUT"
+        run: |
+          VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oP '(?<=version )\d+\.\d+\.\d+')
+          if [[ -z "$VERSION" ]]; then
+            echo "Version not found!" >&2
+            exit 1
+          fi
+          echo "ver=$VERSION" >> "$GITHUB_OUTPUT"
 
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -37,7 +43,7 @@ jobs:
     needs: create-tag
     uses: ./.github/workflows/bundle-linux-x64.yml
 
-  release:
+  git-release:
     runs-on: ubuntu-latest
     needs: [ create-tag, bundle-windows, bundle-linux ]
     steps:
@@ -61,8 +67,10 @@ jobs:
         uses: ncipollo/release-action@v1
         with:
           tag: 'v${{ needs.create-tag.outputs.VERSION }}'
-          artifacts: "artifacts/TestCICD-*,artifacts/testcicd-*,artifacts/testcicd_*"
+          artifacts: "artifacts/ArchitectFX-*,artifacts/architectfx-*,artifacts/architectfx_*"
           bodyFile: 'Changelog.md'
 
-      - name: Release on Maven
-        uses: ./.github/workflows/maven-release.yml
+  maven-release:
+    needs: git-release
+    uses: ./.github/workflows/maven-release.yml
+    secrets: inherit
